/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-icon-item.js
 *   anypoint-icon-item.js
 */

/// <reference path="anypoint-item-shared-styles.d.ts" />

declare namespace AnypointComponents {

  /**
   * `anypoint-icon-item`
   * An Anypoint list item
   */
  class AnypointIconItem extends Polymer.Element {
    connectedCallback(): void;
  }

  /**
   * `anypoint-icon-item`
   * An Anypoint list item
   */
  class AnypointIconItem extends Polymer.Element {
    connectedCallback(): void;
  }
}

interface HTMLElementTagNameMap {
  "anypoint-icon-item": AnypointComponents.AnypointIconItem;
  "anypoint-icon-item": AnypointComponents.AnypointIconItem;
}
