/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-item.js
 *   anypoint-item.js
 */

/// <reference path="anypoint-item-shared-styles.d.ts" />

declare namespace AnypointComponents {

  /**
   * `anypoint-item`
   * An Anypoint list item
   */
  class AnypointItem extends Polymer.Element {
    connectedCallback(): void;
  }

  /**
   * `anypoint-item`
   * An Anypoint list item
   */
  class AnypointItem extends Polymer.Element {
    connectedCallback(): void;
  }
}

interface HTMLElementTagNameMap {
  "anypoint-item": AnypointComponents.AnypointItem;
  "anypoint-item": AnypointComponents.AnypointItem;
}
