/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/AnypointItemBody.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

export {AnypointItemBody};

declare namespace AnypointUi {

  /**
   * `anypoint-item`
   * An Anypoint list item with 2 or 3 lines.
   */
  class AnypointItemBody extends LitElement {
    readonly styles: any;
    legacy: boolean|null|undefined;

    /**
     * Enables compatibility with Anypoint components.
     */
    compatibility: boolean|null|undefined;
    constructor();
    render(): any;
  }
}
