/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/AnypointItem.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

import {ButtonStateMixin, ControlStateMixin, HoverableMixin} from '@anypoint-web-components/anypoint-control-mixins/anypoint-control-mixins.js';

export {AnypointItem};

declare namespace AnypointUi {

  /**
   * `anypoint-item`
   * An Anypoint list item.
   */
  class AnypointItem {
    readonly styles: any;
    legacy: boolean|null|undefined;

    /**
     * Enables compatibility with Anypoint components.
     */
    compatibility: boolean|null|undefined;
    render(): any;
    connectedCallback(): void;
  }
}
