/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/AnypointIconItem.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

import {ButtonStateMixin, ControlStateMixin, HoverableMixin} from '@anypoint-web-components/anypoint-control-mixins/anypoint-control-mixins.js';

export {AnypointIconItem};

declare namespace AnypointUi {

  /**
   * `anypoint-icon-item`
   * An Anypoint icon list item is a convenience element to make an item with icon. It is an
   * interactive list item with a fixed-width icon area.
   * This is useful if the icons are of varying widths, but you want the item
   * bodies to line up. Use this like a `<anypoint-item>`. The child node with the slot
   * name `item-icon` is placed in the icon area.
   */
  class AnypointIconItem {
    readonly styles: any;
    legacy: boolean|null|undefined;

    /**
     * Enables compatibility with Anypoint components.
     */
    compatibility: boolean|null|undefined;
    render(): any;
    connectedCallback(): void;
  }
}
